### ISSUE TITLE
希望尽快适配高版本jdk,目前尝试改动源代码升级到jdk21.启动集群正常，但是CliService工具异常，提示Connection is null when do check!

### ISSUE THREAD

**Issue by zxuanhong** [sofastack/sofa-jraft#1083]
### Your question

1. 系统尽快适配高版本jdk,目前尝试改动源代码使用jdk21.启动集群正常，但是CliService工具异常
2. 提示错误信息Connection is null when do check!。这个异常看起来是网络问题，其实完全不是网络问题。同样的代码，jdk1.8完全正常，jdk21只要操作CliService就会提示这个错误。目前还不知道具体什么问题。
```
2024-03-07 15:07:43  WARN 92029 --- [flow-demo] [rpc-executor #3] com.alipay.sofa.common.log               : check failed. address: 127.0.0.1:19192, connection: null

com.alipay.remoting.exception.RemotingException: Connection is null when do check!
	at com.alipay.remoting.DefaultConnectionManager.check(DefaultConnectionManager.java:354) ~[bolt-1.6.7.jar:na]
	at com.alipay.remoting.rpc.RpcClient.checkConnection(RpcClient.java:447) ~[bolt-1.6.7.jar:na]
	at com.alipay.remoting.rpc.RpcClient.checkConnection(RpcClient.java:438) ~[bolt-1.6.7.jar:na]
	at com.alipay.remoting.rpc.RpcClient.checkConnection(RpcClient.java:433) ~[bolt-1.6.7.jar:na]
	at com.alipay.sofa.jraft.rpc.impl.BoltRpcClient.checkConnection(BoltRpcClient.java:73) ~[main/:na]
	at com.alipay.sofa.jraft.rpc.impl.AbstractClientService.isConnected(AbstractClientService.java:81) ~[main/:na]
	at com.alipay.sofa.jraft.rpc.impl.AbstractClientService.connect(AbstractClientService.java:142) ~[main/:na]
	at com.alipay.sofa.jraft.core.NodeImpl.electSelf(NodeImpl.java:1106) ~[main/:na]
	at com.alipay.sofa.jraft.core.NodeImpl.handleTimeoutNowRequest(NodeImpl.java:3241) ~[main/:na]
	at com.alipay.sofa.jraft.rpc.impl.core.TimeoutNowRequestProcessor.processRequest0(TimeoutNowRequestProcessor.java:52) ~[main/:na]
	at com.alipay.sofa.jraft.rpc.impl.core.TimeoutNowRequestProcessor.processRequest0(TimeoutNowRequestProcessor.java:33) ~[main/:na]
	at com.alipay.sofa.jraft.rpc.impl.core.NodeRequestProcessor.processRequest(NodeRequestProcessor.java:59) ~[main/:na]
	at com.alipay.sofa.jraft.rpc.RpcRequestProcessor.handleRequest(RpcRequestProcessor.java:52) ~[main/:na]
	at com.alipay.sofa.jraft.rpc.RpcRequestProcessor.handleRequest(RpcRequestProcessor.java:34) ~[main/:na]
	at com.alipay.sofa.jraft.rpc.impl.BoltRpcServer$2.handleRequest(BoltRpcServer.java:124) ~[main/:na]
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.dispatchToUserProcessor(RpcRequestProcessor.java:235) ~[bolt-1.6.7.jar:na]
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.doProcess(RpcRequestProcessor.java:146) ~[bolt-1.6.7.jar:na]
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor$ProcessTask.run(RpcRequestProcessor.java:393) ~[bolt-1.6.7.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
```

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
看堆栈似乎是 rpc 层 bolt 报错了

**Comment by zxuanhong** [comment]
@fengjiachun 是的。但是我感觉那边升级每那么快。不过grpc正常😁

**Comment by zxuanhong** [comment]
@fengjiachun 目前jraft-core使用grpc的情况在jdk21下是没问题的😁。

**Comment by fengjiachun** [comment]
> @fengjiachun 目前jraft-core使用grpc的情况在jdk21下是没问题的😁。

👍🏻

**Comment by fengjiachun** [comment]
先 close 了，如果还有问题再打开
