### ISSUE TITLE
RocksDB not work

### ISSUE THREAD

**Issue by Luncert** [sofastack/sofa-jraft#1161]
### Describe the bug

JRaft server fails to start due to RocksDB exception as follow:

```
: java.lang.UnsatisfiedLinkError: /private/var/folders/7s/02wcys893mzgdhv3jfr2x6xh0000gn/T/librocksdbjni4121104413630552895.jnilib: dlopen(/private/var/folders/7s/02wcys893mzgdhv3jfr2x6xh0000gn/T/librocksdbjni4121104413630552895.jnilib, 0x0001): tried: '/private/var/folders/7s/02wcys893mzgdhv3jfr2x6xh0000gn/T/librocksdbjni4121104413630552895.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/7s/02wcys893mzgdhv3jfr2x6xh0000gn/T/librocksdbjni4121104413630552895.jnilib' (no such file), '/private/var/folders/7s/02wcys893mzgdhv3jfr2x6xh0000gn/T/librocksdbjni4121104413630552895.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
        at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.<clinit>(RocksDBLogStorage.java:75)
        at com.alipay.sofa.jraft.core.DefaultJRaftServiceFactory.createLogStorage(DefaultJRaftServiceFactory.java:50)
        at com.alipay.sofa.jraft.core.NodeImpl.initLogStorage(NodeImpl.java:539)
        at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:949)
        at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:135)
        at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitRaftNode(RaftServiceFactory.java:47)
        at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:129)
        at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:107)
```

### Environment

- SOFAJRaft version: 1.3.0
- JVM version (e.g. `java -version`): jbr-17
- OS version (e.g. `uname -a`): Darwin HNWYJ3K2W5 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 20:51:54 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6000 arm64
- Maven version: 3.8.6
- IDE version: Idea

**Comment by fengjiachun** [comment]
This error indicates an architecture mismatch between the RocksDB native library and your system. Specifically, you're trying to run an x86_64 (Intel) version of the RocksDB library on an ARM64 (Apple Silicon) machine.
The key part of the error is:

```
mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')
```

Please upgrade to the latest version of jraft, as it includes a rocksdb library compatible with the ARM platform.

**Comment by Luncert** [comment]
Thanks for reply, JRaft 1.3.15 works for my case.👍
