### ISSUE TITLE
Version conflict between 1.2.6 & earlier

### ISSUE THREAD

**Issue by masaimu** [sofastack/sofa-jraft#237]
### Describe the bug

When I upgrade one rheakv node in a cluster to jraft-rheakv-core 1.2.6 (issue #229), a ClassCastException thrown as below.

I think it's caused by version conflict, maybe we should confirm it. 

```text
2019-08-12 12:50:37,566 [  - /// - ] ERROR storage.KVStoreStateMachine - StateMachine meet critical error: java.lang.ClassCastException: java.lang.Integer cannot be cast to com.alipay.sofa.jraft.rhea.util.Pair
	at com.alipay.sofa.jraft.rhea.storage.KVOperation.getLimit(KVOperation.java:311)
	at com.alipay.sofa.jraft.rhea.storage.BatchRawKVStore.batchScan(BatchRawKVStore.java:126)
	at com.alipay.sofa.jraft.rhea.storage.KVStoreStateMachine.batchApply(KVStoreStateMachine.java:196)
	at com.alipay.sofa.jraft.rhea.storage.KVStoreStateMachine.batchApplyAndRecycle(KVStoreStateMachine.java:149)
	at com.alipay.sofa.jraft.rhea.storage.KVStoreStateMachine.onApply(KVStoreStateMachine.java:118)
	at com.alipay.sofa.jraft.core.FSMCallerImpl.doApplyTasks(FSMCallerImpl.java:534)
	at com.alipay.sofa.jraft.core.FSMCallerImpl.doCommitted(FSMCallerImpl.java:503)
	at com.alipay.sofa.jraft.core.FSMCallerImpl.runApplyTask(FSMCallerImpl.java:431)
	at com.alipay.sofa.jraft.core.FSMCallerImpl.access$100(FSMCallerImpl.java:72)
	at com.alipay.sofa.jraft.core.FSMCallerImpl$ApplyTaskHandler.onEvent(FSMCallerImpl.java:147)
	at com.alipay.sofa.jraft.core.FSMCallerImpl$ApplyTaskHandler.onEvent(FSMCallerImpl.java:141)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:137)
	at java.lang.Thread.run(Thread.java:882)
```

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
Usually `scan` is readIndex read, this bug is triggered by a readIndex read failure leading to the raft log read, when upgrading the new version and launching the application, the raft log is played back(`scan`), resulting exception
