### ISSUE TITLE
IllegalStateException in AbstractBoltClientService

### ISSUE THREAD

**Issue by killme2008** [sofastack/sofa-jraft#319]
### Describe the bug

```
java.lang.IllegalStateException: Client service is not inited.
	at com.alipay.sofa.jraft.rpc.impl.AbstractBoltClientService.connect(AbstractBoltClientService.java:128) ~[classes/:?]
	at com.alipay.sofa.jraft.core.NodeImpl.preVote(NodeImpl.java:2289) ~[classes/:?]
	at com.alipay.sofa.jraft.core.NodeImpl.handleElectionTimeout(NodeImpl.java:540) ~[classes/:?]
	at com.alipay.sofa.jraft.core.NodeImpl.access$1300(NodeImpl.java:131) ~[classes/:?]
	at com.alipay.sofa.jraft.core.NodeImpl$2.onTrigger(NodeImpl.java:725) ~[classes/:?]
	at com.alipay.sofa.jraft.util.RepeatedTimer.run(RepeatedTimer.java:91) ~[classes/:?]
	at com.alipay.sofa.jraft.util.RepeatedTimer.lambda$schedule$0(RepeatedTimer.java:165) ~[classes/:?]
	at com.alipay.sofa.jraft.util.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:597) [classes/:?]
	at com.alipay.sofa.jraft.util.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:665) [classes/:?]
	at com.alipay.sofa.jraft.util.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:397) [classes/:?]
	at java.base/java.lang.Thread.run(Thread.java:834) [?:?]
```

The `rpcClient` has the thread visibility issue here, it's initialized in `synchronized` block, but is not protected by the same object monitor in `connect` and `invokeWithDone` methods etc.

I think the `rpcClient` can be initialized in constructor instead of `init` method to fix this issue.

### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
The problem is not serious, because AbstractBoltClientService is created and initialized when the process starts. This NPE is caused by `shutdown` and then the `connect` method is called. Usually the timer thread.

**Comment by fengjiachun** [comment]
`volatile rpcClient` is enough
