### ISSUE TITLE
mvn test error

### ISSUE THREAD

**Issue by wjiankun** [sofastack/sofa-jraft#390]
使用mvn test过程有些测试用例过不去，但是单独运行某个测试用例 有时可以过 有时不能过
下面是在mvn test过程中报出的错

2020-01-04 12:30:49 [JRaft-Closure-Executor-3] ERROR LogThreadPoolExecutor:88 - Uncaught exception in pool: JRAFT_CLOSURE_EXECUTOR, com.alipay.sofa.jraft.util.MetricThreadPoolExecutor@63c91f53[Running, pool size = 4, active threads = 1, queued tasks = 0, completed tasks = 8054].
java.lang.NullPointerException
	at com.alipay.sofa.jraft.core.Replicator.sendEmptyEntries(Replicator.java:740) ~[classes/:?]
	at com.alipay.sofa.jraft.core.Replicator.sendEmptyEntries(Replicator.java:672) ~[classes/:?]
	at com.alipay.sofa.jraft.core.Replicator.sendHeartbeat(Replicator.java:1576) ~[classes/:?]
	at com.alipay.sofa.jraft.core.Replicator.lambda$onError$20(Replicator.java:986) ~[classes/:?]
	at com.alipay.sofa.jraft.core.Replicator$$Lambda$9/1130588497.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_11]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_11]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_11]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_11]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_11]
---------------------------------------------------------------------------------------
很多时候 在NodeTest测试
testInstallSnapshot 方法测试的时候会出现
Start ensureSame, waitTimes=-1
2020-01-04 20:40:31 [JRaft-RPC-Processor-2] ERROR BoltSession:185 - Fail to copy data, readerId=263074450187599003 fileName=__raft_snapshot_meta offset=0 status=Status[ENOENT<1012>: Fail to find reader=263074450187599003]

环境：
JDK1.8
maven：3.6.3
ideal 2019.2
windows 8.1 专业版
处理器： i7-4500U
内存 8G

**Comment by killme2008** [comment]
这个错误不影响，是 replicator 停止过程中异步关闭没有处理好友好关闭引起的。

目前核心的 NodeTest 测试确实比较依赖时间顺序（为了同步等结果用了比较多的 sleep 之类），所以测试不是特别稳定，在 *nix 系统会相对稳定运行， windows 没有系统测试过。

这块测试后续会想办法优化下。
