### ISSUE TITLE
TestLeaderStopAndReElectWithPriority unittest run failure

### ISSUE THREAD

**Issue by killme2008** [sofastack/sofa-jraft#411]
It happens frequently, maybe we have to investigate it.

```
testLeaderStopAndReElectWithPriority(com.alipay.sofa.jraft.core.NodeTest)  Time elapsed: 7.238 sec  <<< FAILURE!
java.lang.AssertionError: expected:<60> but was:<10>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.alipay.sofa.jraft.core.NodeTest.testLeaderStopAndReElectWithPriority(NodeTest.java:1051)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by zongtanghu** [comment]
This issue can be assigned to me!I will investigate the reason and fix it! @killme2008 @fengjiachun

**Comment by fengjiachun** [comment]
@zongtanghu It's yours

**Comment by fengjiachun** [comment]
any progress? @zongtanghu

**Comment by zongtanghu** [comment]
I look into the findTheNextCandidate method which is in the ReplicatorGroupImpl class.In this method, it will choose the node which logindex is much more enough become leader rather than the node which priority value is larger.

![image](https://user-images.githubusercontent.com/5010883/82790015-e6f39a80-9e9d-11ea-9750-7451b1400c0a.png)

**Comment by zongtanghu** [comment]
So, in this testLeaderStopAndReElectWithPriority method, if the node with priority 10 has more enough logindex file than node with priority 60, the node with priority 10 will be the leader.
