### ISSUE TITLE
UnsatisfiedLinkError when run Counter example on Mac OS.

### ISSUE THREAD

**Issue by tinylcy** [sofastack/sofa-jraft#423]
### Your question

hi,
I have tried to run Counter example on my Mac OS laptop by running this method:

`com.alipay.sofa.jraft.example.counter.CounterServer#main`

the results are as follows, it seems like I have miss some jnilib files, could you tell me how to load these files? thx :)

### Your scenes

Describe your use scenes (why need this feature)
![image](https://user-images.githubusercontent.com/11954488/79738857-ec564600-832f-11ea-8942-ad5f81d9ba8e.png)

```java
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/7g/7stzrc3d04s2_242l2c9nycw0000gn/T/librocksdbjni1311832298353991379.jnilib: dlopen(/private/var/folders/7g/7stzrc3d04s2_242l2c9nycw0000gn/T/librocksdbjni1311832298353991379.jnilib, 1): Symbol not found: __ZdlPvSt11align_val_t
  Referenced from: /private/var/folders/7g/7stzrc3d04s2_242l2c9nycw0000gn/T/librocksdbjni1311832298353991379.jnilib
  Expected in: /usr/lib/libc++.1.dylib
 in /private/var/folders/7g/7stzrc3d04s2_242l2c9nycw0000gn/T/librocksdbjni1311832298353991379.jnilib
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.<clinit>(RocksDBLogStorage.java:75)
	at com.alipay.sofa.jraft.core.DefaultJRaftServiceFactory.createLogStorage(DefaultJRaftServiceFactory.java:50)
	at com.alipay.sofa.jraft.core.NodeImpl.initLogStorage(NodeImpl.java:546)
	at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:962)
	at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:136)
	at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitRaftNode(RaftServiceFactory.java:47)
	at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:129)
	at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:107)
	at com.alipay.sofa.jraft.example.counter.CounterServer.<init>(CounterServer.java:73)
	at com.alipay.sofa.jraft.example.counter.CounterServer.main(CounterServer.java:137)
```

### Environment

- SOFAJRaft version: 1.3.1
- JVM version: jdk1.8.0_171
- OS version : macOS
- Maven version: apache-maven-3.5.3
- IDE version: IntelliJ IDEA 2017

**Comment by killme2008** [comment]
See https://github.com/facebook/rocksdb/issues/5064

**Comment by tinylcy** [comment]
thx.
