### ISSUE TITLE
Install sofaregistry

### ISSUE THREAD

**Issue by xingguangdage** [sofastack/sofa-jraft#428]
java与版本：
# java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
# mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /data/apache-maven-3.3.9
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: /root/jdk1.8.0_171/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1062.1.2.el7.x86_64", arch: "amd64", family: "unix"
操作系统版本：
# uname -a
Linux k8s-master01 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
修改配置文件，178.56.23.11为本机ip
# cat application.properties
nodes.metaNode=DefaultDataCenter:178.56.23.11
nodes.localDataCenter=DefaultDataCenter
nodes.localRegion=DEFAULT_ZONE

安装registry-integration.tgz 5.4.2

启动报错；
[2020-04-26 15:15:52,296][ERROR][main][RegistryApplication] - 178.56.23.11:9615 health check failed.
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1098)
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:428)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:324)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.nodeHealthCheck(RegistryApplication.java:134)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.waitClusterStart(RegistryApplication.java:119)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.main(RegistryApplication.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
[2020-04-26 15:15:52,296][ERROR][main][RegistryApplication] - 178.56.23.11:9615 health check failed.
查看端口无占用情况
# netstat -anultp|grep -w 96[0-9][0-9]
tcp6       0      0 :::9610                 :::*                    LISTEN      7634/java           
tcp6       0      0 :::9611                 :::*                    LISTEN      7634/java           
tcp6       0      0 :::9612                 :::*                    LISTEN      7634/java           
tcp6       0      0 :::9614                 :::*                    LISTEN      7634/java           
tcp6       0      0 :::9615                 :::*                    LISTEN      7634/java           
tcp6       0      0 178.56.23.11:55362     178.56.23.11:9614      ESTABLISHED 7634/java           
tcp6       0      0 178.56.23.11:9614      178.56.23.11:55362     ESTABLISHED 7634/java           
tcp6       0      0 178.56.23.11:38166     178.56.23.11:9615      ESTABLISHED 7634/java           
tcp6       0      0 178.56.23.11:9615      178.56.23.11:38166     ESTABLISHED 7634/java           
# ps -ef|grep 7634
root      7634     1  8 15:14 pts/2    00:00:20 java -Dregistry.integration.home=/data/registry-integration -Dspring.config.location=/data/registry-integration/conf/application.properties -Duser.home=/data/registry-integration -server -Xms512m -Xmx512m -Xmn256m -Xss256k -XX:+DisableExplicitGC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:/data/registry-integration/logs/registry-integration-gc.log -verbose:gc -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/registry-integration/logs -XX:ErrorFile=/data/registry-integration/logs/registry-integration-hs_err_pid%p.log -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -jar /data/registry-integration/registry-integration.jar --logging.config=/data/registry-integration/conf/logback-spring.xml
root      8371  7099  0 15:18 pts/2    00:00:00 grep --color=auto 7634

**Comment by xingguangdage** [comment]
提错地方了

**Comment by xingguangdage** [comment]
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1098)
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:428)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:324)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.nodeHealthCheck(RegistryApplication.java:134)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.waitClusterStart(RegistryApplication.java:119)
        at com.alipay.sofa.registry.server.integration.RegistryApplication.main(RegistryApplication.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
[2020-04-27 19:35:53,083][ERROR][main][RegistryApplication] - 172.27.255.41:9615 health check failed.
