### ISSUE TITLE
Counter example not supported grpc

### ISSUE THREAD

**Issue by shibd** [sofastack/sofa-jraft#451]
### Describe the bug

我尝试在Counter中增加grpc的实现，启动报错。我在counter的resource文件中输出了`raft.desc`。经过排查，发现这个类`ProtobufMsgFactory`只能加载最新的`raft.desc`，如果我在应用中声明了这个文件，那么`jraft-core`包中的文件将加载不到。
```
Exception in thread "main" java.lang.NullPointerException: null default instance: com.alipay.sofa.jraft.rpc.RpcRequests$AppendEntriesRequest
	at com.alipay.sofa.jraft.util.Requires.requireNonNull(Requires.java:55)
	at com.alipay.sofa.jraft.rpc.impl.GrpcServer.registerProcessor(GrpcServer.java:94)
	at com.alipay.sofa.jraft.rpc.RaftRpcServerFactory.addRaftRequestProcessors(RaftRpcServerFactory.java:101)
	at com.alipay.sofa.jraft.rpc.RaftRpcServerFactory.createRaftRpcServer(RaftRpcServerFactory.java:75)
	at com.alipay.sofa.jraft.rpc.RaftRpcServerFactory.createRaftRpcServer(RaftRpcServerFactory.java:61)
	at com.alipay.sofa.jraft.example.counter.CounterServer.<init>(CounterServer.java:53)
	at com.alipay.sofa.jraft.example.counter.CounterServer.main(CounterServer.java:136)
```

### Expected behavior
`ProtobufMsgFactory`应该要能加载`*.desc`的文件

### Actual behavior
`ProtobufMsgFactory `只能加载`raft.desc`的文件

### Minimal yet complete reproducer code (or GitHub URL to code)
参见：https://github.com/shibd/sofa-jraft/pull/3

### Environment

- SOFAJRaft version: master
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): mac os
- Maven version: 
- IDE version:

**Comment by fengjiachun** [comment]
jraft-core之外的不应该依靠 ProtobufMsgFactory 来加载，
参考如下方式：
两步：
1. com.alipay.sofa.jraft.rpc.impl.GrpcRaftRpcFactory#registerProtobufSerializer 注册 request 和 response proto
2. com.alipay.sofa.jraft.rpc.impl.MarshallerHelper#registerRespInstance 注册 request 和response 的映射关系

**Comment by shibd** [comment]
> jraft-core之外的不应该依靠 ProtobufMsgFactory 来加载，
> 参考如下方式：
> 两步：
> 
> 1. com.alipay.sofa.jraft.rpc.impl.GrpcRaftRpcFactory#registerProtobufSerializer 注册 request 和 response proto
> 2. com.alipay.sofa.jraft.rpc.impl.MarshallerHelper#registerRespInstance 注册 request 和response 的映射关系

好的，谢谢。用这个后没问题了，跑通了。https://github.com/shibd/sofa-jraft/pull/3
