### ISSUE TITLE
RheaKV 集群服务器cpu飙升问题

### ISSUE THREAD

**Issue by guotaisu** [sofastack/sofa-jraft#502]
描述：通过rest api 压测10000 请求 jraft get api
现象：cpu飙升

堆栈：

"Bolt-default-executor-4-thread-3" #45 daemon prio=5 os_prio=0 tid=0x00007fc9ac30b800 nid=0x5aa4 waiting on condition [0x00007fc97c690000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c04be258> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"Bolt-default-executor-4-thread-2" #44 daemon prio=5 os_prio=0 tid=0x00007fc9c9ae4000 nid=0x5aa3 waiting on condition [0x00007fc97d792000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c04be258> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"Rpc-netty-server-worker-7-thread-3" #43 daemon prio=5 os_prio=0 tid=0x00007fc9c9ae1800 nid=0x5aa2 runnable [0x00007fc97e894000]
   java.lang.Thread.State: RUNNABLE
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:101)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:304)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:355)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"Rpc-netty-server-worker-7-thread-2" #42 daemon prio=5 os_prio=0 tid=0x00007fc9c9ae0000 nid=0x5aa1 runnable [0x00007fc97e995000]
   java.lang.Thread.State: RUNNABLE
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:101)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:304)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:355)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)

相关参数配置：
    int cores = 32;
    int readIndexCoreThreads            = Math.max(cores << 2, 16);
    int leaderStateTriggerCoreThreads   = 4;
    int snapshotCoreThreads             = 1;
    int snapshotMaxThreads              = 32;
    int cliRpcCoreThreads               = cores << 2;
    int raftRpcCoreThreads              = Math.max(cores << 3, 32);
    int kvRpcCoreThreads                = Math.max(cores << 3, 32);
    int callbackExecutorCorePoolSize    = cores << 2;
    int callbackExecutorMaximumPoolSize = cores << 3;

将上述参数调成1/2，集群tps 下降到 1/10，仍然存在大量锁等待。

**Comment by fengjiachun** [comment]
cpu 高的线程是什么？用 [arthas](https://arthas.aliyun.com/doc/thread.html) thread -n 的 cmd 看一下

另外最好再提供一下 metrics，如何输出 metrics 见[这个链接第11章节](https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/)

**Comment by fengjiachun** [comment]
没有后续就关闭了

**Comment by guotaisu** [comment]
好的 先关闭 后续整理一下数据 谢谢
