### ISSUE TITLE
 c.a.s.j.c.StateMachineAdapter            : onStartFollowing: LeaderChangeContext [leaderId=192.168.12.1:8181, term=774, status=Status[ENEWLEADER<10011>: Follower receives message from new leader with the same term.]].

### ISSUE THREAD

**Issue by bobbylv** [sofastack/sofa-jraft#537]

**Comment by killme2008** [comment]
你的网络环境是不是经常分区？ 看看 onLeaderStop 的日志。另外你的版本号是多少。

**Comment by bobbylv** [comment]
这个集群是在同一个交换机上的，版本是1.3.4，因为公司对内存要求比较严苛，所以调低了raftOptions的 disruptorBufferSize大小，不知道是否会有影响

**Comment by bobbylv** [comment]
这个集群的3台机器是在同一个交换机上的，版本是1.3.4，因为公司对内存要求比较严苛，所以调低了raftOptions的interruptorBufferSize大小，不知道是否会有影响，也限制了-Djraft.available_processors = 2只用2个cpu来控制池的大小

**Comment by killme2008** [comment]
你去看下日志里 leader 的  onLeaderStop 字样的日志以及前后的日志，会有说明为什么 leader 会 step down，这是核心的原因。通常来说就是心跳超时之类。

**Comment by bobbylv** [comment]
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[?:1.8.0_181]
	at com.alipay.sofa.jraft.rhea.client.FutureHelper.get(FutureHelper.java:46) ~[jraft-rheakv-core-1.3.4.jar!/:?]
	at com.alipay.sofa.jraft.rhea.client.DefaultRheaKVStore.bMultiGet(YccmRheaKVStore.java:346) ~[classes!/:2.0.0.0]
日志会看到比较都这个异常又是为啥呢？

**Comment by killme2008** [comment]
@bobbylv 这就是超时，核心是为啥超时，你可以看下网络连通性和 JVM gc 是否正常，超时是可以适当调大。

**Comment by bobbylv** [comment]
2020-11-26 11:40:37.583  WARN 8714 --- [rheakv-read-index-callback #8] c.a.s.j.r.s.RaftRawKVStore               : Fail to [multiGet] with 'ReadIndex': Status[ETIMEDOUT<1010>: read-index request timeout].
2020-11-26 11:40:37.583 ERROR 8714 --- [rheakv-read-index-callback #8] c.a.s.j.r.s.KVClosureAdapter             : Fail status: Status[ETIMEDOUT<1010>: read-index request timeout].
2020-11-26 11:40:37.583  WARN 8714 --- [rheakv-read-index-callback #8] c.a.s.j.r.c.f.i.FailoverClosureImpl      : [Failover] status: Status[ETIMEDOUT<1010>: read-index request timeout], error: LEADER_NOT_AVAILABLE, [2] retries left.
因为内存设置得比较小gc会比较频繁

**Comment by killme2008** [comment]
election timeout 也建议加大，默认值是比较小的
