### ISSUE TITLE
GetExample throw TimeoutException

### ISSUE THREAD

**Issue by superzjcy** [sofastack/sofa-jraft#545]
Exception in thread "main" java.util.concurrent.TimeoutException 	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771) 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) 	at com.alipay.sofa.jraft.rhea.client.FutureHelper.get(FutureHelper.java:46) 	at com.alipay.sofa.jraft.rhea.client.DefaultRheaKVStore.bPut(DefaultRheaKVStore.java:986) 	at com.alipay.sofa.jraft.example.rheakv.GetExample.get(GetExample.java:47) 	at com.alipay.sofa.jraft.example.rheakv.GetExample.main(GetExample.java:40) 2021-01-03 12:58:55 [Bolt-default-executor-4-thread-3] INFO  NamedThreadFactory:82 - Creates new Thread[rheakv-rpc-callback #0,5,main].

**Comment by fengjiachun** [comment]
超时原因要看一下，在 server 端

**Comment by fengjiachun** [comment]
没有其他信息就先 close 了
