### ISSUE TITLE
某个follow节点下线后，leader出现reject异常，上层业务日志发送失败

### ISSUE THREAD

**Issue by liu2008aaa** [sofastack/sofa-jraft#549]
### Your question

Closure的线程池满了后导致上层业务提交失败/超时

### Your scenes

1.集群初始4个节点
2.其中一个follow节点宕机一段时间(10分钟+)
3.在这10分钟内业务端不断有较高的数据提交请求(业务客户端有10个线程持续请求)
4.最终业务端会有提交失败或超时现象
相关日志：
```
 2021-01-21 07:58:14.402 [ ] [JRaft-NodeImpl-Disruptor-0] [handleEventException-65] ERROR c.a.s.j.u.LogExceptionHandler - Handle NodeImpl disruptor event error, event is com.alipay.sofa.jraft.core.NodeImpl$LogEntryAndClosure@358f8d94 
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@7532b849 rejected from com.alipay.sofa.jraft.util.MetricThreadPoolExecutor@424cdda0[Running, pool size = 100, active threads = 100, queued tasks = 0, completed task
s = 1780930]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at com.alipay.sofa.jraft.util.Utils.runInThread(Utils.java:157)
        at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.wakeupAllWaiter(LogManagerImpl.java:405)
        at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.appendEntries(LogManagerImpl.java:345)
        at com.alipay.sofa.jraft.core.NodeImpl.executeApplyingTasks(NodeImpl.java:1358)
        at com.alipay.sofa.jraft.core.NodeImpl.access$200(NodeImpl.java:137)
        at com.alipay.sofa.jraft.core.NodeImpl$LogEntryAndClosureHandler.onEvent(NodeImpl.java:282)
        at com.alipay.sofa.jraft.core.NodeImpl$LogEntryAndClosureHandler.onEvent(NodeImpl.java:262)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:137)
        at java.lang.Thread.run(Thread.java:748)
2021-01-21 07:58:16.349 [ ] [JRaft-Closure-Executor-74] [afterExecute-90] ERROR c.a.s.j.u.LogThreadPoolExecutor - Uncaught exception in pool: JRAFT_CLOSURE_EXECUTOR, com.alipay.sofa.jraft.util.MetricThreadPoolExecutor@424cdda0[Running, pool size = 10
0, active threads = 99, queued tasks = 0, completed tasks = 1780932]. 
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@777aa8e2 rejected from com.alipay.sofa.jraft.util.MetricThreadPoolExecutor@424cdda0[Running, pool size = 100, active threads = 100, queued tasks = 0, completed task
s = 1780931]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at com.alipay.sofa.jraft.util.Utils.runInThread(Utils.java:157)
        at com.alipay.sofa.jraft.util.Utils.runClosureInThread(Utils.java:169)
        at com.alipay.sofa.jraft.rpc.impl.AbstractClientService.invokeWithDone(AbstractClientService.java:57)
        at com.alipay.sofa.jraft.rpc.impl.AbstractClientService.invokeWithDone(AbstractClientService.java:57)
        at com.alipay.sofa.jraft.rpc.impl.core.DefaultRaftClientService.appendEntries(DefaultRaftClientService.java:105)
        at com.alipay.sofa.jraft.core.Replicator.sendEntries(Replicator.java:1578)
        at com.alipay.sofa.jraft.core.Replicator.sendEntries(Replicator.java:1493)
        at com.alipay.sofa.jraft.core.Replicator.continueSending(Replicator.java:918)
        at com.alipay.sofa.jraft.core.Replicator.lambda$waitMoreEntries$8(Replicator.java:1476)
        at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.runOnNewLog(LogManagerImpl.java:1128)
        at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.lambda$wakeupAllWaiter$6(LogManagerImpl.java:405)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2021-01-21 07:58:17.205 [ ] [JRaft-NodeImpl-Disruptor-0] [checkAndResolveConflict-1008] WARN c.a.s.j.s.i.LogManagerImpl - Received entries of which the lastLog=0 is not greater than appliedIndex=599256, return immediately with nothing changed. 
2021-01-21 07:58:17.351 [ ] [JRaft-Closure-Executor-67] [onAppendEntriesReturned-1348] WARN c.a.s.j.c.Replicator - Fail to issue RPC to pub-native-d:8004, consecutiveErrorTimes=10, error=Status[EINTERNAL<1004>: Fail to send a RPC request:com.alipay.remoting.exception.RemotingException: Create connection failed. The address is pub-native-d:8004] 
2021-01-21 07:58:27.372 [ ] [JRaft-Closure-Executor-64] [onHeartbeatReturned-1115] WARN c.a.s.j.c.Replicator - Fail to issue RPC to pub-native-d:8004, consecutiveErrorTimes=20, error=Status[EINTERNAL<1004>: Fail to send a RPC request:com.alipay.remoting.exception.RemotingException: Create connection failed. The address is pub-native-d:8004] 
2021-01-21 07:58:37.394 [ ] [JRaft-Closure-Executor-64] [onHeartbeatReturned-1115] WARN c.a.s.j.c.Replicator - Fail to issue RPC to pub-native-d:8004, consecutiveErrorTimes=30, error=Status[EINTERNAL<1004>: Fail to send a RPC request:com.alipay.remot
```

### Your advice

1.很明显Closure的线程都去跟失联的节点通信去了，看过之前的帖子说是[线程池](https://github.com/sofastack/sofa-jraft/issues/426)已经做了隔离了，是不是线程池隔离的不彻底，导致append流程中还有用到Closure的线程池的地方。
2.看到提过一个方案是由业务方做节点的剔除，这个我们暂时不好接受。
3.希望隔离的彻底一点，总之不希望由于失联的节点而影响集群的工作(在满足协议算法条件下)。
4.或者针对失联节点做个降级处理？减少通信频率？

### Environment

- SOFAJRaft version:1.3.3
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
猜测是 leader 尝试与宕机 follower 尝试建立 TCP 连接是被 block （bolt 老版本会阻塞建连），升级 jraft 到 [1.3.4 ](https://github.com/sofastack/sofa-jraft/releases/tag/1.3.4)版本以上再试下

或者就直接升级到最新版本

**Comment by liu2008aaa** [comment]
好的，我们试一下，感谢回复

**Comment by liu2008aaa** [comment]
回复一下，使用最新版本[1.3.5](https://github.com/sofastack/sofa-jraft/releases/tag/1.3.5)后没再出现上述问题，再次感谢！
