### ISSUE TITLE
testInstallLargeSnapshotWithThrottle is flaky 

### ISSUE THREAD

**Issue by alievmirza** [sofastack/sofa-jraft#664]
### Describe the bug
Test `com.alipay.sofa.jraft.core.NodeTest#testInstallLargeSnapshotWithThrottle` is flaky. It is needed to run this test approxiamtely 20 times to get this error 

```
2021-08-11 19:16:57 [JRaft-Closure-Executor-7] ERROR Utils:180 - Fail to run done closure
java.lang.AssertionError: Status[ECATCHUP<10003>: Peer 172.25.4.112:5006 failed to catch up.]
	at org.junit.Assert.fail(Assert.java:89) ~[junit-4.13.1.jar:4.13.1]
	at org.junit.Assert.assertTrue(Assert.java:42) ~[junit-4.13.1.jar:4.13.1]
	at com.alipay.sofa.jraft.core.NodeTest.lambda$testInstallLargeSnapshotWithThrottle$1(NodeTest.java:2194) ~[test-classes/:?]
	at com.alipay.sofa.jraft.util.Utils$1.run(Utils.java:178) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_231]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
```

The first time we encountered this failed test in our fork, we changed RPC layer in our repo, so as far as we reproduced this also in the original JRaft repo, I would say that this bug is not related to the network layer. I've also made some investigations on our side, I've recorded messages on the leader and we can see that right before the fail leader for some reason sent last two `AppendEntriesRequest` with an interval that is more than election timeout. As far as I can understand, that affects `lastRpcSendTimestamp` and further check for a catch-up does not pass and ends with an error 
```
Utils.monotonicMs() - this.replicatorGroup.getLastRpcSendTimestamp(peer) <= this.options
                    .getElectionTimeoutMs()
```

I can provide full debug logs, If it is needed

### Expected behavior
Node is successfully joined to the cluster with throttled snapshot and the test is not flaky

### Actual behavior
Test `testInstallLargeSnapshotWithThrottle` is flaky, and there is a chance that node cannot join the topology successfully 

### Steps to reproduce
Just run `testInstallLargeSnapshotWithThrottle` several time (~20) on the last matser revision (34af4e21cf976f7d5499634bf74f5686c5a70677).

### Environment

- SOFAJRaft version: 1.3.8
- JVM version (e.g. `java -version`):
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
- OS version (e.g. `uname -a`):
macOS Catalina 10.15.7
- Maven version:
Apache Maven 3.6.3
- IDE version:
Intellij IDEA 2019.3.5

**Comment by alievmirza** [comment]
I've made some investigation and seems that I found the root cause, there is a race in `com.alipay.sofa.jraft.util.ThreadId#setError`
 
When we try to get `com.alipay.sofa.jraft.util.ThreadId#lock` in `com.alipay.sofa.jraft.util.ThreadId#setError`, the lock may be held by `com.alipay.sofa.jraft.core.Replicator#onCatchUpTimedOut`. Hence tryLock will be false
https://github.com/sofastack/sofa-jraft/blob/34af4e21cf976f7d5499634bf74f5686c5a70677/jraft-core/src/main/java/com/alipay/sofa/jraft/util/ThreadId.java#L160
and we put error in `pendingErrors`
https://github.com/sofastack/sofa-jraft/blob/34af4e21cf976f7d5499634bf74f5686c5a70677/jraft-core/src/main/java/com/alipay/sofa/jraft/util/ThreadId.java#L170

However, another thread has already called `id.unlock` in `onCatchUpTimedOut` before we put an error in `pendingErrors`, so that means that heartbeat will be handled in the next call of `id.unlock`, which happens on the next `onCatchUpTimedOut` call, and it happens after election time out, so catch up is failed.

I propose to  add synchronization on `pendingErrors` in `com.alipay.sofa.jraft.util.ThreadId#setError`. I'll prepare PR for that

You can see the logs that prove this hypothesis: 

```
TRACE onCatchUpTimedOut BEFORE id.lock(); 2021-08-17T13:22:12.027Z th = Thread[JRaft-Node-Scheduler-127.0.0.1:5003-6,10,main]
TRACE setError BEFORE this.lock.tryLock() 2021-08-17T13:22:12.027Z th = Thread[JRaft-Node-Scheduler-127.0.0.1:5003-4,10,main]
TRACE onCatchUpTimedOut BEFORE id.unlock();; 2021-08-17T13:22:12.027Z th = Thread[JRaft-Node-Scheduler-127.0.0.1:5003-6,10,main]
2021-08-17 16:22:12:027 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-5][NodeImpl] Node <unitest/127.0.0.1:5003> waits peer 127.0.0.1:5006 to catch up.
2021-08-17 16:22:12:027 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-6][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5004 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:027 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-3][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5005 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:028 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-0][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5005 prevLogIndex=2001 prevLogTerm=1
TRACE setError BEFORE this.pendingErrors.add(errorCode); 2021-08-17T13:22:12.027Z th = Thread[JRaft-Node-Scheduler-127.0.0.1:5003-4,10,main]
2021-08-17 16:22:12:028 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-1][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5004 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:092 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-7][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5005 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:092 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-4][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5004 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:093 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-0][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5005 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:093 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-1][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5004 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:146 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5006-3][CopySession] Send get file request 
2021-08-17 16:22:12:147 +0300 [INFO][JRaft-Request-Processor-127.0.0.1:5003-25][FileService] handleGetFile id=28120602076208, name=data, offset=23552, cnt=128
2021-08-17 16:22:12:147 +0300 [DEBUG][JRaft-Request-Processor-127.0.0.1:5003-25][FileService] GetFile from 127.0.0.1:5006 path=target/work/ITNodeTest/testInstallLargeSnapshotWithThrottle_1629206501553/127.0.0.1_5003/snapshot/snapshot_2001 filename=data offset=23552 count=128
2021-08-17 16:22:12:157 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-0][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5004 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:157 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-2][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5005 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:158 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-0][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5005 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:158 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-1][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5004 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:223 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-5][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5004 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:224 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-1][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5005 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:224 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-0][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5005 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:224 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-1][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5004 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:289 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-3][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5005 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:289 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-6][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5004 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:290 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-1][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5004 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:290 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-0][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5005 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:355 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-4][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5005 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:355 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-7][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5004 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:356 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-1][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5004 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:356 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-0][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5005 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:419 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-0][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5004 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:419 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-2][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5005 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:420 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-0][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5005 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:420 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-1][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5004 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:482 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-5][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5005 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:482 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-1][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5004 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:483 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-0][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5005 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:483 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-1][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5004 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:548 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-6][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5004 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:548 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-3][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5005 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:549 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-0][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5005 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:549 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-1][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5004 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:612 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-7][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5004 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:612 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-4][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5005 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:613 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-0][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5005 prevLogIndex=2001 prevLogTerm=1
2021-08-17 16:22:12:613 +0300 [DEBUG][JRaft-AppendEntries-Processor-127.0.0.1:5003-1][Replicator] Node unitest:127.0.0.1:5003 received HeartbeatResponse from 127.0.0.1:5004 prevLogIndex=2001 prevLogTerm=1
TRACE onCatchUpTimedOut BEFORE id.lock(); 2021-08-17T13:22:12.628Z th = Thread[JRaft-Node-Scheduler-127.0.0.1:5003-14,10,main]
TRACE onCatchUpTimedOut BEFORE id.unlock();; 2021-08-17T13:22:12.628Z th = Thread[JRaft-Node-Scheduler-127.0.0.1:5003-14,10,main]
TRACE onError BEFORE id.unlock(); 2021-08-17T13:22:12.628Z th = Thread[JRaft-Node-Scheduler-127.0.0.1:5003-14,10,main]
2021-08-17 16:22:12:628 +0300 [WARNING][JRaft-Common-Executor-127.0.0.1:5003-0][NodeImpl] Node <unitest/127.0.0.1:5003> caughtUp failed, status=Status[ETIMEDOUT<1010>: ETIMEDOUT], peer=127.0.0.1:5006.
2021-08-17 16:22:12:628 +0300 [DEBUG][JRaft-Common-Executor-127.0.0.1:5003-2][Replicator] Node <unitest/127.0.0.1:5003> send HeartbeatRequest to 127.0.0.1:5006 term 1 lastCommittedIndex 2001
2021-08-17 16:22:12:629 +0300 [WARNING][JRaft-Common-Executor-127.0.0.1:5003-0][NodeImpl] Node <unitest/127.0.0.1:5003> fail to catch up peer 127.0.0.1:5006 when trying to change peers from [127.0.0.1:5003, 127.0.0.1:5004, 127.0.0.1:5005] to [127.0.0.1:5003, 127.0.0.1:5004, 127.0.0.1:5005, 127.0.0.1:5006].
2021-08-17 16:22:12:629 +0300 [INFO][JRaft-Common-Executor-127.0.0.1:5003-0][ReplicatorGroupImpl] Stop replicator to 127.0.0.1:5006.
2021-08-17 16:22:12:630 +0300 [INFO][JRaft-Common-Executor-127.0.0.1:5003-0][Replicator] Replicator Replicator [state=Snapshot, statInfo=<running=INSTALLING_SNAPSHOT, firstLogIndex=1, lastLogIncluded=2001, lastLogIndex=0, lastTermIncluded=1>, peerId=127.0.0.1:5006, type=Follower] is going to quit
2021-08-17 16:22:12:637 +0300 [ERROR][JRaft-Common-Executor-127.0.0.1:5003-0][Utils] Fail to run done closure
org.opentest4j.AssertionFailedError: status = 
Status[ECATCHUP<10003>: Peer 127.0.0.1:5006 failed to catch up.] ==> expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:46)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:170)
```

**Comment by killme2008** [comment]
@alievmirza  Good catch! We will reivew your patch ,thanks a lot.
