### ISSUE TITLE
ThreadId unlock race problem.

### ISSUE THREAD

**Issue by horizonzy** [sofastack/sofa-jraft#668]
### Your question
The log show that the ThreadId#unlock lock race problem.

```
2021-08-23 15:31:12.954 [JRaft-Closure-Executor-5] WARN  com.alipay.sofa.jraft.util.ThreadId - Fail to unlock with Replicator [state=Replicate, statInfo=<running=IDLE, firstLogIndex=31719693, lastLogIncluded=0,
 lastLogIndex=31719693, lastTermIncluded=0>, peerId=172.xx.xx.xx:8000, type=Follower], the lock is held by null and current thread is Thread[JRaft-Closure-Executor-5,5,main].
2021-08-23 15:31:56.796 [JRaft-Closure-Executor-5] WARN  com.alipay.sofa.jraft.util.ThreadId - Fail to unlock with Replicator [state=Replicate, statInfo=<running=IDLE, firstLogIndex=31720638, lastLogIncluded=0,
 lastLogIndex=31720638, lastTermIncluded=0>, peerId=172.xx.xx.xx:8000, type=Follower], the lock is held by null and current thread is Thread[JRaft-Closure-Executor-5,5,main].
2021-08-23 15:33:29.049 [Append-Entries-Thread-Send2] WARN  com.alipay.sofa.jraft.util.ThreadId - Fail to unlock with Replicator [state=Replicate, statInfo=<running=IDLE, firstLogIndex=31722623, lastLogIncluded
=0, lastLogIndex=31722623, lastTermIncluded=0>, peerId=172.xx.xx.xx:8000, type=Follower], the lock is held by null and current thread is Thread[Append-Entries-Thread-Send2,5,main].
2021-08-23 15:36:29.083 [Append-Entries-Thread-Send2] WARN  com.alipay.sofa.jraft.util.ThreadId - Fail to unlock with Replicator [state=Replicate, statInfo=<running=APPENDING_ENTRIES, firstLogIndex=31726525, la
stLogIncluded=0, lastLogIndex=31726525, lastTermIncluded=0>, peerId=172.xx.xx.xx:8000, type=Follower], the lock is held by null and current thread is Thread[Append-Entries-Thread-Send2,5,main].
2021-08-23 15:37:08.344 [Append-Entries-Thread-Send2] WARN  com.alipay.sofa.jraft.util.ThreadId - Fail to unlock with Replicator [state=Replicate, statInfo=<running=IDLE, firstLogIndex=31727385, lastLogIncluded
=0, lastLogIndex=31727385, lastTermIncluded=0>, peerId=172.xx.xx.xx:8000, type=Follower], the lock is held by null and current thread is Thread[Append-Entries-Thread-Send2,5,main].
2021-08-23 15:37:31.381 [Append-Entries-Thread-Send2] WARN  com.alipay.sofa.jraft.util.ThreadId - Fail to unlock with Replicator [state=Replicate, statInfo=<running=IDLE, firstLogIndex=31727881, lastLogIncluded
=0, lastLogIndex=31727881, lastTermIncluded=0>, peerId=172.xx.xx.xx:8000, type=Follower], the lock is held by null and current thread is Thread[Append-Entries-Thread-Send2,5,main].
2021-08-23 15:38:36.225 [Append-Entries-Thread-Send2] WARN  com.alipay.sofa.jraft.util.ThreadId - Fail to unlock with Replicator [state=Replicate, statInfo=<running=IDLE, firstLogIndex=31729302, lastLogIncluded
=0, lastLogIndex=31729302, lastTermIncluded=0>, peerId=172.xx.xx.xx:8000, type=Follower], the lock is held by null and current thread is Thread[Append-Entries-Thread-Send2,5,main].
2021-08-23 15:38:58.454 [JRaft-Closure-Executor-0] WARN  com.alipay.sofa.jraft.util.ThreadId - Fail to unlock with Replicator [state=Replicate, statInfo=<running=IDLE, firstLogIndex=31729765, lastLogIncluded=0,
 lastLogIndex=31729765, lastTermIncluded=0>, peerId=172.xx.xx.xx:8000, type=Follower], the lock is held by null and current thread is Thread[JRaft-Closure-Executor-0,5,main].
2021-08-23 15:39:38.543 [JRaft-Closure-Executor-5] WARN  com.alipay.sofa.jraft.util.ThreadId - Fail to unlock with Replicator [state=Replicate, statInfo=<running=IDLE, firstLogIndex=31730651, lastLogIncluded=0,
 lastLogIndex=31730651, lastTermIncluded=0>, peerId=172.xx.xx.xx:8000, type=Follower], the lock is held by null and current thread is Thread[JRaft-Closure-Executor-5,5,main].
2021-08-23 15:39:46.396 [JRaft-Closure-Executor-5] WARN  com.alipay.sofa.jraft.util.ThreadId - Fail to unlock with Replicator [state=Replicate, statInfo=<running=IDLE, firstLogIndex=31730809, lastLogIncluded=0,
 lastLogIndex=31730809, lastTermIncluded=0>, peerId=172.xx.xx.xx:8000, type=Follower], the lock is held by null and current thread is Thread[JRaft-Closure-Executor-5,5,main].
2021-08-23 15:41:35.497 [JRaft-Closure-Executor-0] WARN  com.alipay.sofa.jraft.util.ThreadId - Fail to unlock with Replicator [state=Replicate, statInfo=<running=IDLE, firstLogIndex=31733166, lastLogIncluded=0,
 lastLogIndex=31733166, lastTermIncluded=0>, peerId=172.xx.xx.xx:8000, type=Follower], the lock is held by null and current thread is Thread[JRaft-Closure-Executor-0,5,main].
2021-08-23 15:42:03.811 [JRaft-Closure-Executor-1] WARN  com.alipay.sofa.jraft.util.ThreadId - Fail to unlock with Replicator [state=Replicate, statInfo=<running=IDLE, firstLogIndex=31733795, lastLogIncluded=0,
 lastLogIndex=31733795, lastTermIncluded=0>, peerId=172.xx.xx.xx:8000, type=Follower], the lock is held by null and current thread is Thread[JRaft-Closure-Executor-1,5,main].
2021-08-23 15:42:29.181 [JRaft-Closure-Executor-4] WARN  com.alipay.sofa.jraft.util.ThreadId - Fail to unlock with Replicator [state=Replicate, statInfo=<running=IDLE, firstLogIndex=31734340, lastLogIncluded=0, lastLogIndex=31734340, lastTermIncluded=0>, peerId=172.xx.xx.xx:8000, type=Follower], the lock is held by null and current thread is Thread[JRaft-Closure-Executor-4,5,main].
2021-08-23 15:43:06.119 [JRaft-Closure-Executor-1] WARN  com.alipay.sofa.jraft.util.ThreadId - Fail to unlock with Replicator [state=Replicate, statInfo=<running=IDLE, firstLogIndex=31735141, lastLogIncluded=0, lastLogIndex=31735141, lastTermIncluded=0>, peerId=172.xx.xx.xx:8000, type=Follower], the lock is held by null and current thread is Thread[JRaft-Closure-Executor-1,5,main].

```

So I use arthas to get stack info when NonReentrantLock#isHeldByCurrentThread return `false`. 

```
[arthas@32474]$ stack com.alipay.sofa.jraft.util.NonReentrantLock isHeldByCurrentThread 'returnObj==false'
Press Q or Ctrl+C to abort.
Affect(class count: 1 , method count: 1) cost in 116 ms, listenerId: 11
ts=2021-08-23 16:04:33;thread_name=JRaft-Closure-Executor-5;id=bc;is_daemon=true;priority=5;TCCL=sun.misc.Launcher$AppClassLoader@55f96302
    @com.alipay.sofa.jraft.util.NonReentrantLock.isHeldByCurrentThread()
        at com.alipay.sofa.jraft.util.ThreadId.unlock(ThreadId.java:98)
        at com.alipay.sofa.jraft.core.Replicator.onError(Replicator.java:1067)
        at com.alipay.sofa.jraft.util.ThreadId.unlock(ThreadId.java:115)
        at com.alipay.sofa.jraft.core.Replicator.waitMoreEntries(Replicator.java:1552)
        at com.alipay.sofa.jraft.core.Replicator.sendEntries(Replicator.java:1616)
        at com.alipay.sofa.jraft.core.Replicator.sendEntries(Replicator.java:1566)
        at com.alipay.sofa.jraft.core.Replicator.continueSending(Replicator.java:991)
        at com.alipay.sofa.jraft.core.Replicator.lambda$waitMoreEntries$9(Replicator.java:1549)
        at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.runOnNewLog(LogManagerImpl.java:1137)
        at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.lambda$wakeupAllWaiter$6(LogManagerImpl.java:405)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

ts=2021-08-23 16:05:11;thread_name=JRaft-Closure-Executor-6;id=bd;is_daemon=true;priority=5;TCCL=sun.misc.Launcher$AppClassLoader@55f96302
    @com.alipay.sofa.jraft.util.NonReentrantLock.isHeldByCurrentThread()
        at com.alipay.sofa.jraft.util.ThreadId.unlock(ThreadId.java:98)
        at com.alipay.sofa.jraft.core.Replicator.onError(Replicator.java:1067)
        at com.alipay.sofa.jraft.util.ThreadId.unlock(ThreadId.java:115)
        at com.alipay.sofa.jraft.core.Replicator.waitMoreEntries(Replicator.java:1552)
        at com.alipay.sofa.jraft.core.Replicator.sendEntries(Replicator.java:1616)
        at com.alipay.sofa.jraft.core.Replicator.sendEntries(Replicator.java:1566)
        at com.alipay.sofa.jraft.core.Replicator.continueSending(Replicator.java:991)
        at com.alipay.sofa.jraft.core.Replicator.lambda$waitMoreEntries$9(Replicator.java:1549)
        at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.runOnNewLog(LogManagerImpl.java:1137)
        at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.lambda$wakeupAllWaiter$6(LogManagerImpl.java:405)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

ts=2021-08-23 16:05:17;thread_name=JRaft-Closure-Executor-5;id=bc;is_daemon=true;priority=5;TCCL=sun.misc.Launcher$AppClassLoader@55f96302
    @com.alipay.sofa.jraft.util.NonReentrantLock.isHeldByCurrentThread()
        at com.alipay.sofa.jraft.util.ThreadId.unlock(ThreadId.java:98)
        at com.alipay.sofa.jraft.core.Replicator.onError(Replicator.java:1067)
        at com.alipay.sofa.jraft.util.ThreadId.unlock(ThreadId.java:115)
        at com.alipay.sofa.jraft.core.Replicator.waitMoreEntries(Replicator.java:1552)
        at com.alipay.sofa.jraft.core.Replicator.sendEntries(Replicator.java:1616)
        at com.alipay.sofa.jraft.core.Replicator.sendEntries(Replicator.java:1566)
        at com.alipay.sofa.jraft.core.Replicator.continueSending(Replicator.java:991)
        at com.alipay.sofa.jraft.core.Replicator.lambda$waitMoreEntries$9(Replicator.java:1549)
        at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.runOnNewLog(LogManagerImpl.java:1137)
        at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.lambda$wakeupAllWaiter$6(LogManagerImpl.java:405)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

ts=2021-08-23 16:05:50;thread_name=Append-Entries-Thread-Send2;id=105;is_daemon=true;priority=5;TCCL=sun.misc.Launcher$AppClassLoader@55f96302
    @com.alipay.sofa.jraft.util.NonReentrantLock.isHeldByCurrentThread()
        at com.alipay.sofa.jraft.util.ThreadId.unlock(ThreadId.java:98)
        at com.alipay.sofa.jraft.core.Replicator.onError(Replicator.java:1067)
        at com.alipay.sofa.jraft.util.ThreadId.unlock(ThreadId.java:115)
        at com.alipay.sofa.jraft.core.Replicator.sendEmptyEntries(Replicator.java:815)
        at com.alipay.sofa.jraft.core.Replicator.sendEmptyEntries(Replicator.java:743)
        at com.alipay.sofa.jraft.core.Replicator.onAppendEntriesReturned(Replicator.java:1474)
        at com.alipay.sofa.jraft.core.Replicator.onRpcReturned(Replicator.java:1326)
        at com.alipay.sofa.jraft.core.Replicator$4.run(Replicator.java:1658)
        at com.alipay.sofa.jraft.rpc.impl.AbstractClientService$1.complete(AbstractClientService.java:241)
        at com.alipay.sofa.jraft.rpc.impl.GrpcClient$1.lambda$onNext$0(GrpcClient.java:152)
        at com.alipay.sofa.jraft.util.concurrent.MpscSingleThreadExecutor$Worker.runTask(MpscSingleThreadExecutor.java:352)
        at com.alipay.sofa.jraft.util.concurrent.MpscSingleThreadExecutor$Worker.run(MpscSingleThreadExecutor.java:336)
        at com.alipay.sofa.jraft.util.concurrent.MpscSingleThreadExecutor.lambda$doStartWorker$3(MpscSingleThreadExecutor.java:263)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by fengjiachun** [comment]
ThreadId#unlock 里的那个循环 onError 里 unlock 了应该

**Comment by killme2008** [comment]
嗯，这个可以避免掉，但是暂时也不影响

**Comment by killme2008** [comment]
已经解决，发布 1.3.10
