### ISSUE TITLE
使用CliService#resetPeer，导致写metadata文件失败

### ISSUE THREAD

**Issue by horizonzy** [sofastack/sofa-jraft#669]
### Describe the bug
raft配置3个节点。127.0.0.1:8000，127.0.0.1:8001，127.0.0.1:8002.

本地启动127.0.0.1:8000这个节点。然后调用接口resetPeers改变127.0.0.1:8000中的所有节点为自己一个节点 127.0.0.1:8000.

然后抛出异常:
```
2021-08-24 22:30:01.522 [JRaft-Global-ElectionTimer11] ERROR c.a.sofa.jraft.storage.impl.LocalRaftMetaStorage - Fail to save raft meta
java.nio.channels.ClosedByInterruptException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:392)
	at com.alipay.sofa.jraft.util.Utils.fsync(Utils.java:390)
	at com.alipay.sofa.jraft.storage.io.ProtoBufFile.save(ProtoBufFile.java:121)
	at com.alipay.sofa.jraft.storage.impl.LocalRaftMetaStorage.save(LocalRaftMetaStorage.java:118)
	at com.alipay.sofa.jraft.storage.impl.LocalRaftMetaStorage.setTermAndVotedFor(LocalRaftMetaStorage.java:188)
	at com.alipay.sofa.jraft.core.NodeImpl.electSelf(NodeImpl.java:1182)
	at com.alipay.sofa.jraft.core.NodeImpl.preVote(NodeImpl.java:2686)
	at com.alipay.sofa.jraft.core.NodeImpl.handleElectionTimeout(NodeImpl.java:639)
	at com.alipay.sofa.jraft.core.NodeImpl.access$1300(NodeImpl.java:139)
	at com.alipay.sofa.jraft.core.NodeImpl$2.onTrigger(NodeImpl.java:938)
	at com.alipay.sofa.jraft.util.RepeatedTimer.run(RepeatedTimer.java:86)
	at com.alipay.sofa.jraft.util.RepeatedTimer.lambda$schedule$0(RepeatedTimer.java:182)
	at com.alipay.sofa.jraft.util.timer.DefaultTimer$TimeoutTask.run(DefaultTimer.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

问题原因:
由于只有自己一个节点，electionTimeout执行preVote时，会在当前线程中直接进行electSelf，需要注意的是，当前线程是由electionTimer触发，是electionTimer中的线程，这是问题的根本原因。

https://github.com/sofastack/sofa-jraft/blob/a1c22fa92cee70bfdbde76bd48aa7b137d48e326/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L2684

然后在electSelf中, 会将electionTimer给stop，在stop的过程中，其实会把electionTimer的线程给interrupt，interupt就会出问题。
https://github.com/sofastack/sofa-jraft/blob/a1c22fa92cee70bfdbde76bd48aa7b137d48e326/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L1135

然后就是去写metadata文件，这里是通过fileChannel.force操作去同步写，同步写有一个要求，就是当前线程不能被interupt，否则就会抛出异常。
https://github.com/sofastack/sofa-jraft/blob/a1c22fa92cee70bfdbde76bd48aa7b137d48e326/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L1180

https://github.com/sofastack/sofa-jraft/blob/a1c22fa92cee70bfdbde76bd48aa7b137d48e326/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/io/ProtoBufFile.java#L121

https://github.com/sofastack/sofa-jraft/blob/a1c22fa92cee70bfdbde76bd48aa7b137d48e326/jraft-core/src/main/java/com/alipay/sofa/jraft/util/Utils.java#L390

正常多节点没问题，因为多节点的回调是在rpc的回调线程中。
单节点直接启动也没问题，因为单节点启动时是在主线程中进行，也没问题。

**Comment by fengjiachun** [comment]
是不是可以在 stop 里清除一下中断标志即可？

**Comment by killme2008** [comment]
这个异常应该没有实质性影响

**Comment by horizonzy** [comment]
有些影响，这里写文件失败，会给状态机设置error.

**Comment by fengjiachun** [comment]
默认 jraft 参数应该没有这个问题，
是因为使用了 sharedTimer，sharedTimer 的 DefaultTimer在 cancel 一个 task 的时候对线程设置了中断标志，其实可以改下，cancel 后清除中断标志就行

**Comment by horizonzy** [comment]
是的，我将electionTimer设置成了global的。
