### ISSUE TITLE
不关闭程序进程，通过API关闭jraft服务，关闭成功，但重新通过API启动,报错。改如何正确关闭jraft服务？如何重新启动？

### ISSUE THREAD

**Issue by SpringLin97** [sofastack/sofa-jraft#715]
启动的代码
![image](https://user-images.githubusercontent.com/63085858/141607496-5e233409-9b03-4d07-8cd8-8fb739d09de8.png)
关闭的代码
![image](https://user-images.githubusercontent.com/63085858/141607522-2713dad1-f84c-4416-8b63-e0446618c2e2.png)
关闭成功
![image](https://user-images.githubusercontent.com/63085858/141607544-9c0af16c-6b32-4c83-b2b6-7877ecb2cf25.png)
重新调用启动脚本，启动失败
![image](https://user-images.githubusercontent.com/63085858/141607551-b73de6ed-f232-4ff1-9683-08affa9f77fc.png)
2021-11-13 13:49:44 [Thread-1] ERROR RocksDBLogStorage:207 - Fail to init RocksDBLogStorage, path=/tmp/server1\log.
org.rocksdb.RocksDBException: Failed to create lock file: /tmp/server1\log/LOCK: Áíһ¸ö³ÌÐòÕýÔÚʹÓôËÎļþ£¬½ø³ÌÎ
	at org.rocksdb.RocksDB.open(Native Method) ~[rocksdbjni-5.18.4.jar:?]
	at org.rocksdb.RocksDB.open(RocksDB.java:286) ~[rocksdbjni-5.18.4.jar:?]
	at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.openDB(RocksDBLogStorage.java:308) ~[jraft-core-1.3.8.jar:?]
	at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.initAndLoad(RocksDBLogStorage.java:226) ~[jraft-core-1.3.8.jar:?]
	at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.init(RocksDBLogStorage.java:205) ~[jraft-core-1.3.8.jar:?]
	at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.init(RocksDBLogStorage.java:70) ~[jraft-core-1.3.8.jar:?]
	at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.init(LogManagerImpl.java:184) ~[jraft-core-1.3.8.jar:?]
	at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.init(LogManagerImpl.java:77) ~[jraft-core-1.3.8.jar:?]
	at com.alipay.sofa.jraft.core.NodeImpl.initLogStorage(NodeImpl.java:589) ~[jraft-core-1.3.8.jar:?]
	at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:999) ~[jraft-core-1.3.8.jar:?]
	at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:139) ~[jraft-core-1.3.8.jar:?]
	at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitRaftNode(RaftServiceFactory.java:47) ~[jraft-core-1.3.8.jar:?]
	at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:129) ~[jraft-core-1.3.8.jar:?]
	at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:107) ~[jraft-core-1.3.8.jar:?]
	at com.visec.core.util.test.server.TestServer.<init>(TestServer.java:75) ~[classes/:?]
	at com.visec.core.util.test.server.TestServer.start(TestServer.java:138) ~[classes/:?]
	at com.visec.core.util.test.util.Util.startServer(Util.java:118) ~[classes/:?]
	at com.visec.core.util.test.RunTest.lambda$main$1(RunTest.java:47) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-11-13 13:49:44 [Thread-1] ERROR LogManagerImpl:185 - Fail to init logStorage
2021-11-13 13:49:44 [Thread-1] ERROR NodeImpl:1000 - Node <test/127.0.0.1:8081> initLogStorage failed.

**Comment by tsgmq** [comment]
试试this.node.shutdown();这个呢

**Comment by SpringLin97** [comment]
> 试试this.node.shutdown();这个呢

也不行，
java.lang.IllegalStateException: ERROR: Failed to start the Server!
	at com.alipay.remoting.AbstractRemotingServer.startup(AbstractRemotingServer.java:104)
	at com.alipay.sofa.jraft.rpc.impl.BoltRpcServer.init(BoltRpcServer.java:50)
	at com.alipay.sofa.jraft.rpc.impl.BoltRpcServer.init(BoltRpcServer.java:37)
	at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:131)
	at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:107)
	at com.visec.core.util.test.server.TestServer.<init>(TestServer.java:75)
	at com.visec.core.util.test.server.TestServer.start(TestServer.java:138)
	at com.visec.core.util.test.util.Util.startServer(Util.java:119)
	at com.visec.core.util.test.RunTest2.lambda$main$1(RunTest2.java:44)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 1 more

**Comment by SpringLin97** [comment]
> 试试this.node.shutdown();这个呢

如果用springboot项目跑，调用this.node.shutdown();
同样出现文件锁
![1636946232(1)](https://user-images.githubusercontent.com/63085858/141716864-1e4c0fd5-91f8-4008-8b5c-b5ce62236e9f.jpg)

**Comment by killme2008** [comment]
你是不是启动了多个节点？ 每个节点都要调用 shutdown 的。

**Comment by killme2008** [comment]
注意的一点是 node 的 shutdown 是一个异步方法，要等待所有过程结束可以在 shutdown 后调用 node.join() 同步等待。异步版本是 shutdown(closure) 可以传入一个闭包，当所有服务关闭的时候会回调这个闭包通知。
