### ISSUE TITLE
jraft调用this.node.shutdown()方法，然后再调用this.raftGroupService.start();,出现端口占用，端口没有清理干净

### ISSUE THREAD

**Issue by SpringLin97** [sofastack/sofa-jraft#717]
### **java.lang.IllegalStateException: ERROR: Failed to start the Server!**
	at com.alipay.remoting.AbstractRemotingServer.startup(AbstractRemotingServer.java:104)
	at com.alipay.sofa.jraft.rpc.impl.BoltRpcServer.init(BoltRpcServer.java:50)
	at com.alipay.sofa.jraft.rpc.impl.BoltRpcServer.init(BoltRpcServer.java:37)
	at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:131)
	at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:107)
	at com.visec.core.util.test.server.TestServer.<init>(TestServer.java:75)
	at com.visec.core.util.test.server.TestServer.start(TestServer.java:138)
	at com.visec.core.util.test.util.Util.startServer(Util.java:119)
	at com.visec.core.util.test.RunTest2.lambda$main$1(RunTest2.java:44)
	at java.lang.Thread.run(Thread.java:748)
### **Caused by: java.net.BindException: Address already in use: bind**
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 1 more

**Comment by killme2008** [comment]
`RaftGroupService` 也有单独的 `shutdown` 方法，会关闭启动的 rpc server。
