### ISSUE TITLE
jraft 发生死锁

### ISSUE THREAD

**Issue by Cczzzz** [sofastack/sofa-jraft#720]
场景：nacos 2.0.3 
jraft版本：1.35
描述：
3节点组成的nacos 集群，在重启后，进行压测后，其中一个nacos节点假死。jstack 后发现近乎所有线程都卡在获取NodeImpl 的读写锁。
观察jstack 发现有一个线程获取到写锁后堵塞在另外一个锁上。

"Append-Entries-Thread-Send5" #2118 daemon prio=5 os_prio=0 cpu=114476.72ms elapsed=289723.84s tid=0x00007fe194e41800 nid=0x153c runnable  [0x00007fe0ba545000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.12/Native Method)
	- parking to wait for  <0x00000007056c9df0> (a com.alipay.sofa.jraft.util.NonReentrantLock)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.12/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireNanos(java.base@11.0.12/AbstractQueuedSynchronizer.java:980)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireNanos(java.base@11.0.12/AbstractQueuedSynchronizer.java:1288)
	at com.alipay.sofa.jraft.util.NonReentrantLock.tryLock(NonReentrantLock.java:48)
	at com.alipay.sofa.jraft.util.ThreadId.lock(ThreadId.java:79)
	at com.alipay.sofa.jraft.core.Replicator.getNextIndex(Replicator.java:1778)
	at com.alipay.sofa.jraft.core.ReplicatorGroupImpl.findTheNextCandidate(ReplicatorGroupImpl.java:282)
	at com.alipay.sofa.jraft.core.ReplicatorGroupImpl.stopAllAndFindTheNextCandidate(ReplicatorGroupImpl.java:253)
	at com.alipay.sofa.jraft.core.NodeImpl.stepDown(NodeImpl.java:1290)
	at com.alipay.sofa.jraft.core.NodeImpl.onError(NodeImpl.java:2484)
	at com.alipay.sofa.jraft.core.FSMCallerImpl.setError(FSMCallerImpl.java:704)
	at com.alipay.sofa.jraft.core.FSMCallerImpl.enqueueTask(FSMCallerImpl.java:236)
	at com.alipay.sofa.jraft.core.FSMCallerImpl.onCommitted(FSMCallerImpl.java:245)
	at com.alipay.sofa.jraft.core.BallotBox.commitAt(BallotBox.java:137)
	at com.alipay.sofa.jraft.core.Replicator.onAppendEntriesReturned(Replicator.java:1428)
	at com.alipay.sofa.jraft.core.Replicator.onRpcReturned(Replicator.java:1258)
	at com.alipay.sofa.jraft.core.Replicator$4.run(Replicator.java:1589)
	at com.alipay.sofa.jraft.rpc.impl.AbstractClientService$1.complete(AbstractClientService.java:241)
	at com.alipay.sofa.jraft.rpc.impl.GrpcClient$1.lambda$onNext$0(GrpcClient.java:152)
	at com.alipay.sofa.jraft.rpc.impl.GrpcClient$1$$Lambda$655/0x00000008008fe840.run(Unknown Source)
	at com.alipay.sofa.jraft.util.concurrent.MpscSingleThreadExecutor$Worker.runTask(MpscSingleThreadExecutor.java:352)
	at com.alipay.sofa.jraft.util.concurrent.MpscSingleThreadExecutor$Worker.run(MpscSingleThreadExecutor.java:336)
	at com.alipay.sofa.jraft.util.concurrent.MpscSingleThreadExecutor.lambda$doStartWorker$3(MpscSingleThreadExecutor.java:263)
	at com.alipay.sofa.jraft.util.concurrent.MpscSingleThreadExecutor$$Lambda$659/0x00000008008fdc40.run(Unknown Source)
	at java.lang.Thread.run(java.base@11.0.12/Thread.java:829)
这是它的堆栈，线程堵塞在Replicator # getNextIndex 1778 行

什么情况会导致发生这样的堵塞，是否是版本太低的bug

**Comment by Cczzzz** [comment]
[jstack.log](https://github.com/sofastack/sofa-jraft/files/7554739/jstack.log)

**Comment by Cczzzz** [comment]
在nacos 控制台显示
 "errMsg": "Error [type=ERROR_TYPE_STATE_MACHINE, status=Status[EBUSY<1009>: FSMCaller is overload.]]"
这应该是jraft 返回的状态

**Comment by killme2008** [comment]
@Cczzzz 这是状态机已经过载了，单个 raft group 承载的写入量是有限的。性能建议可以参考用户指南第九节 https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/

**Comment by killme2008** [comment]
看了下堆栈，这里确实有一个死锁的隐患，不过起因也是因为状态机过载了，状态机 apply 速度跟不上。这里的锁机制可以优化下，不过最终还是要避免过载，进入过载后目前唯一的恢复方式就是重启节点。

**Comment by Cczzzz** [comment]
> 看了下堆栈，这里确实有一个死锁的隐患，不过起因也是因为状态机过载了，状态机 apply 速度跟不上。这里的锁机制可以优化下，不过最终还是要避免过载，进入过载后目前唯一的恢复方式就是重启节点。

能详细讲下死锁的隐患 ，这个事情吗。我们在排查问题，想知道引起死锁的详细原因

**Comment by Cczzzz** [comment]
对于 jraft 有好用的监控方式吗

**Comment by killme2008** [comment]
> > 看了下堆栈，这里确实有一个死锁的隐患，不过起因也是因为状态机过载了，状态机 apply 速度跟不上。这里的锁机制可以优化下，不过最终还是要避免过载，进入过载后目前唯一的恢复方式就是重启节点。
> 
> 能详细讲下死锁的隐患 ，这个事情吗。我们在排查问题，想知道引起死锁的详细原因

晚点我理个思路给你。

**Comment by killme2008** [comment]
> 对于 jraft 有好用的监控方式吗

支持metric， 看第 8 节，你可以接入到你喜欢的监控系统 https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/

**Comment by Cczzzz** [comment]
> > > 看了下堆栈，这里确实有一个死锁的隐患，不过起因也是因为状态机过载了，状态机 apply 速度跟不上。这里的锁机制可以优化下，不过最终还是要避免过载，进入过载后目前唯一的恢复方式就是重启节点。
> > 
> > 
> > 能详细讲下死锁的隐患 ，这个事情吗。我们在排查问题，想知道引起死锁的详细原因
> 
> 晚点我理个思路给你。

好，感谢

**Comment by killme2008** [comment]
1.3.10 已经发布，引入了反压模式解决这个问题了
