### ISSUE TITLE
[ReconnectManager$HealConnectionRunner#166] [Thread-15] reconnect target: Origin url [172.19.0.5:8181], Unique key [172.19.0.5:8181]. failed.

### ISSUE THREAD

**Issue by monkeysungit** [sofastack/sofa-jraft#743]
### Your question

删掉的节点还是一直心跳请求，报错

### Your scenes

[ReconnectManager$HealConnectionRunner#166] [Thread-15] reconnect target: Origin url [172.19.0.5:8181], Unique key [172.19.0.5:8181]. failed.
java.lang.RuntimeException: com.alipay.remoting.exception.RemotingException: Create connection failed. The address is 172.19.0.5:8181
	at com.alipay.remoting.ReconnectManager$ReconnectTask.run(ReconnectManager.java:186)
	at com.alipay.remoting.ReconnectManager$HealConnectionRunner.run(ReconnectManager.java:154)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.alipay.remoting.exception.RemotingException: Create connection failed. The address is 172.19.0.5:8181
	at com.alipay.remoting.DefaultConnectionManager.create(DefaultConnectionManager.java:513)
	at com.alipay.remoting.DefaultConnectionManager.doCreate(DefaultConnectionManager.java:816)
	at com.alipay.remoting.DefaultConnectionManager.access$000(DefaultConnectionManager.java:52)
	at com.alipay.remoting.DefaultConnectionManager$ConnectionPoolCall.call(DefaultConnectionManager.java:744)
	at com.alipay.remoting.DefaultConnectionManager$ConnectionPoolCall.call(DefaultConnectionManager.java:710)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.alipay.remoting.util.RunStateRecordedFutureTask.run(RunStateRecordedFutureTask.java:39)
	at com.alipay.remoting.DefaultConnectionManager.getConnectionPoolAndCreateIfAbsent(DefaultConnectionManager.java:602)
	at com.alipay.remoting.DefaultConnectionManager.createConnectionAndHealIfNeed(DefaultConnectionManager.java:494)
	at com.alipay.remoting.ReconnectManager$ReconnectTask.run(ReconnectManager.java:184)
	... 2 common frames omitted
Caused by: java.lang.Exception: Create connection to 172.19.0.5:8181 error!
	at com.alipay.remoting.connection.AbstractConnectionFactory.doCreateConnection(AbstractConnectionFactory.java:264)
	at com.alipay.remoting.connection.AbstractConnectionFactory.createConnection(AbstractConnectionFactory.java:157)
	at com.alipay.remoting.DefaultConnectionManager.create(DefaultConnectionManager.java:510)
	... 11 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: No route to host: /172.19.0.5:8181
Caused by: java.net.ConnectException: finishConnect(..) failed: No route to host
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124)
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:243)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:660)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:637)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:524)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:492)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:745)
2021-12-13 10:16:49,738 WARN  [AbstractConnectionFactory#263] [Thread-15] Create connection to 172.19.0.5:8181 error!
### Environment

- SOFAJRaft version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
删掉的节点是通过 removePeer 吗？如果是，按照如下步骤检查：

1. 找到 leader 节
2. 执行 `kill -s -SIGUSR2 pid` 
2. 进程目录会产生一个 node_describe.log.XXX 的文件，查看 conf 字段中是否包含你删除的节点，包含的话证明没删成功，注意下 removePeer 返回的结果 [用户文档第十一小节](https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/)
