### ISSUE TITLE
在Counter例子中使用Grpc报错

### ISSUE THREAD

**Issue by Zhanghailin1995** [sofastack/sofa-jraft#748]
### Your question
在跑example的Counter例子时，我使用了jraft-extension的grpc模块，节点是无法启动的，这是设计如此，还是bug？问题出在registerProcessor时这个parserClasses是找不到对应的request的实例的
```
@SuppressWarnings("unchecked")
    @Override
    public void registerProcessor(final RpcProcessor processor) {
        final String interest = processor.interest();
        final Message reqIns = Requires.requireNonNull(this.parserClasses.get(interest), "null default instance: " + interest);
```

### Your scenes
```
2021-12-23 21:07:19 [main] INFO  JRaftServiceLoader:275 - SPI service [com.alipay.sofa.jraft.JRaftServiceFactory - com.alipay.sofa.jraft.core.DefaultJRaftServiceFactory] loading.
2021-12-23 21:07:19 [main] INFO  JRaftServiceLoader:275 - SPI service [com.alipay.sofa.jraft.rpc.RaftRpcFactory - com.alipay.sofa.jraft.rpc.impl.GrpcRaftRpcFactory] loading.
Exception in thread "main" java.lang.NullPointerException: null default instance: com.alipay.sofa.jraft.example.counter.rpc.GetValueRequest
	at com.alipay.sofa.jraft.util.Requires.requireNonNull(Requires.java:55)
	at com.alipay.sofa.jraft.rpc.impl.GrpcServer.registerProcessor(GrpcServer.java:133)
	at com.alipay.sofa.jraft.example.counter.CounterServer.<init>(CounterServer.java:57)
	at com.alipay.sofa.jraft.example.counter.CounterServer.main(CounterServer.java:137)
```

### Environment

- SOFAJRaft version: master版本
- JVM version (e.g. `java -version`): jdk8
- OS version (e.g. `uname -a`): win10
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
嗯，确实是这样的， Counter 的 example 是基于 bolt rpc 开发的，并且 message 用的是 hessian 序列化，增加了 gRPC 后仅支持 protobuf 的序列化/反序列化方式，这也是这里报错的原因，当前建议先换成 bolt 运行这个 example 吧，后面我们会支持下 gRPC 运行这个 example
