### ISSUE TITLE
不支持arm64架构上运行

### ISSUE THREAD

**Issue by a364176773** [sofastack/sofa-jraft#776]
### Describe the bug

```
java.lang.UnsatisfiedLinkError: /private/var/folders/7y/4wqm1bg50g52kd60gg_nkcz40000gn/T/librocksdbjni5021292562757409203.jnilib: dlopen(/private/var/folders/7y/4wqm1bg50g52kd60gg_nkcz40000gn/T/librocksdbjni5021292562757409203.jnilib, 0x0001): tried: '/private/var/folders/7y/4wqm1bg50g52kd60gg_nkcz40000gn/T/librocksdbjni5021292562757409203.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/librocksdbjni5021292562757409203.jnilib' (no such file)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
	at java.lang.Runtime.load0(Runtime.java:811)
	at java.lang.System.load(System.java:1088)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:79)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:57)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:69)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:38)
	at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.<clinit>(RocksDBLogStorage.java:75)
	at com.alipay.sofa.jraft.core.DefaultJRaftServiceFactory.createLogStorage(DefaultJRaftServiceFactory.java:50)
	at com.alipay.sofa.jraft.core.NodeImpl.initLogStorage(NodeImpl.java:579)
```
### Environment

- SOFAJRaft version: 1.3.9
- JVM version (e.g. `java -version`): jdk8
- OS version (e.g. `uname -a`): macos 12.1
- Maven version:
- IDE version:

**Comment by a364176773** [comment]
> jdk 是谁家的？ 用 oracle 的试试

zuul的jdk8
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (Zulu 8.50.0.1017-CA-macos-aarch64) (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (Zulu 8.50.0.1017-CA-macos-aarch64) (build 25.275-b01, mixed mode)

**Comment by fengjiachun** [comment]
换 oracle jdk 就好了，我也是 apple m1，运行没问题

**Comment by a364176773** [comment]
> 换 oracle jdk 就好了，我也是 apple m1，运行没问题

好的谢谢
