### ISSUE TITLE
[BUG] `NodeImpl#executeApplyingTasks` maybe NPE

### ISSUE THREAD

**Issue by haoyann** [sofastack/sofa-jraft#814]
### Describe the bug
The user set `done` maybe is null, so `done.run(st)` will throw NPE.

https://github.com/sofastack/sofa-jraft/blob/092913645ffc4795e7e52f82e9d595bf86ba3ab9/jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java#L1364-L1370

```
java.lang.NullPointerException: null
	at com.alipay.sofa.jraft.core.NodeImpl.lambda$executeApplyingTasks$3(NodeImpl.java:1368) ~[jraft-core-1.3.10.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_271]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_271]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_271]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_271]
```

**Comment by haoyann** [comment]
PR merged close.
