### ISSUE TITLE
How to know the possible reason of snapshot shot saving file operation failure?

### ISSUE THREAD

**Issue by mareden** [sofastack/sofa-jraft#820]
### Your question
After introducing snapshot saving/loading, sometimes there's IOException. Unfortunately, the exception isn't clear enough to indicate the reason or possible cause of the issue. From the log, I saw that the file moving operation fails, but there's no further reason for the failure (e.g. possible reason like disk is full, or source file doesn't exist, etc.), and also the exception stack for the IOException wasn't shown fullly (at the code line where the exception was raised, com/alipay/sofa/jraft/util/Utils at line 341).
Can I get your support to know what's the possible reason for the IO Exception? for 'error: data/raft/modern_0418/temp/__raft_snapshot_meta.tmp -> data/raft/modern_0418/temp/__raft_snapshot_meta'

### Your scenes
There's snapshot saving issue:
```
2022-04-19 11:28:52,659 JRaft-Closure-Executor-38 WARN  [Utils:341] Unable to move atomically, falling back to non-atomic move, error: data/raft/modern_0418/temp/__raft_snapshot_meta.tmp -> data/raft/modern_0418/temp/__raft_snapshot_meta.
2022-04-19 11:28:52,659 JRaft-Closure-Executor-38 WARN  [Utils:352] Unable to move data/raft/modern_0418/temp/__raft_snapshot_meta.tmp to data/raft/modern_0418/temp/__raft_snapshot_meta. Attempting to delete data/raft/modern_0418/temp/__raft_snapshot_meta.tmp and abandoning.
2022-04-19 11:28:52,660 JRaft-Closure-Executor-38 ERROR [LocalSnapshotStorage:212] Fail to sync writer data/raft/modern_0418/temp.
2022-04-19 11:28:52,660 JRaft-Closure-Executor-38 INFO  [LocalSnapshotStorage:167] Deleting snapshot data/raft/modern_0418/temp.
2022-04-19 11:28:52,660 JRaft-Closure-Executor-38 ERROR [SnapshotExecutorImpl:398] Fail to close writer
java.io.IOException
        at com.alipay.sofa.jraft.storage.snapshot.local.LocalSnapshotStorage.close(LocalSnapshotStorage.java:251)
        at com.alipay.sofa.jraft.storage.snapshot.local.LocalSnapshotWriter.close(LocalSnapshotWriter.java:98)
        at com.alipay.sofa.jraft.storage.snapshot.local.LocalSnapshotWriter.close(LocalSnapshotWriter.java:93)
        at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl.onSnapshotSaveDone(SnapshotExecutorImpl.java:396)
        at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl$SaveSnapshotDone.continueRun(SnapshotExecutorImpl.java:145)
        at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl$SaveSnapshotDone.lambda$run$0(SnapshotExecutorImpl.java:141)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Describe your use scenes (why need this feature)

### Your advice

Describe the advice or solution you'd like

### Environment

- SOFAJRaft version: 1.3.7
- JVM version (e.g. `java -version`): 1.8.0_181-b13
- OS version (e.g. `uname -a`): Linux 173604 3.10.0-957.el7.x86_64 #1 SMP Sat Dec 15 12:48:25 CST 2018 x86_64 x86_64 x86_64 GNU/Linux
- Maven version: 
- IDE version:

**Comment by mareden** [comment]
Thanks for your quick answer. Will have a try to to upgrade to latest version.
I'm closing this question for now, and in case there's further questsion, this question might be reopened or new one might be raised.

**Comment by mareden** [comment]
I've just updated to latest version 1.3.10.bugfix_2, unfortunately, I saw that the code keeps the same with previous version 1.3.7, and it's expected that exactly the same output message will be given, like following:
```
Unable to move atomically, falling back to non-atomic move, error: data/raft/modern_0418/temp/__raft_snapshot_meta.tmp -> data/raft/modern_0418/temp/__raft_snapshot_meta.
```

code:  (Utils.java, Line 352~356):
```
            if (e instanceof AtomicMoveNotSupportedException) {
                LOG.warn("Atomic move not supported, falling back to non-atomic move, error: {}.", e.getMessage());
            } else {
                LOG.warn("Unable to move atomically, falling back to non-atomic move, error: {}.", e.getMessage());
            }
```

**Comment by mareden** [comment]
I'tll be appreciated if we can get your help on this. @fengjiachun , thanks.

**Comment by fengjiachun** [comment]
https://github.com/sofastack/sofa-jraft/blame/master/jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/local/LocalSnapshotStorage.java#L212

LocalSnapshotStorage#212  made the exception message to be lost.

**Comment by killme2008** [comment]
The log `Fail to sync writer .... ` should have the stack trace right now , please attach the log.

**Comment by mareden** [comment]
@fengjiachun @killme2008 My fault to reopen this thread after checking the source code of Utils.java only. Now I know code in LocalSnapshotStorage, which will caught the exeption, has been updated as described.
Actually, the error mentioned in this thread is randomly raised. I haven't seen the error again after updating to latest version. Will check the log and update this thread in case the exception is caught.
Again, I'll close this question temporarily, and will add comment with exception details or reopen this question if it's needed.
Thank you both.

**Comment by mareden** [comment]
@fengjiachun @killme2008 now I'm seeing snapshot saving error again, and following is the log:
```
2022-05-31 12:12:14,891 JRaft-Closure-Executor-14 WARN  [Utils:341] Unable to move atomically, falling back to non-atomic move, error: data/raft/data_snapshot/snapshot_0530/temp/__raft_snapshot_meta.tmp -> data/raft/data_snapshot/snapshot_0530/temp/__raft_snapshot_meta.
2022-05-31 12:12:14,891 JRaft-Closure-Executor-14 INFO  [Utils:345] The target file data/raft/data_snapshot/snapshot_0530/temp/__raft_snapshot_meta was already existing.
2022-05-31 12:12:14,892 JRaft-Closure-Executor-14 WARN  [Utils:352] Unable to move data/raft/data_snapshot/snapshot_0530/temp/__raft_snapshot_meta.tmp to data/raft/data_snapshot/snapshot_0530/temp/__raft_snapshot_meta. Attempting to delete data/raft/data_snapshot/snapshot_0530/temp/__raft_snapshot_meta.tmp and abandoning.
2022-05-31 12:12:14,892 JRaft-Closure-Executor-14 ERROR [LocalSnapshotStorage:212] Fail to sync writer data/raft/data_snapshot/snapshot_0530/temp.
2022-05-31 12:12:14,892 JRaft-Closure-Executor-14 INFO  [LocalSnapshotStorage:167] Deleting snapshot data/raft/data_snapshot/snapshot_0530/temp.
2022-05-31 12:12:14,896 JRaft-Closure-Executor-14 ERROR [SnapshotExecutorImpl:398] Fail to close writer
java.io.IOException
        at com.alipay.sofa.jraft.storage.snapshot.local.LocalSnapshotStorage.close(LocalSnapshotStorage.java:251)
        at com.alipay.sofa.jraft.storage.snapshot.local.LocalSnapshotWriter.close(LocalSnapshotWriter.java:98)
        at com.alipay.sofa.jraft.storage.snapshot.local.LocalSnapshotWriter.close(LocalSnapshotWriter.java:93)
        at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl.onSnapshotSaveDone(SnapshotExecutorImpl.java:396)
        at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl$SaveSnapshotDone.continueRun(SnapshotExecutorImpl.java:145)
        at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl$SaveSnapshotDone.lambda$run$0(SnapshotExecutorImpl.java:141)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2022-05-31 12:12:14,898 JRaft-FSMCaller-Disruptor-0 ERROR [StateMachineAdapter:72] Encountered an error=Status[EIO<1014>: Fail to save snapshot.] on StateMachine com.server.handlers.StateMachine, it's highly recommended to implement this method as raft stops working since some error occurs, you should figure out the cause and repair or remove this node.
Error [type=ERROR_TYPE_SNAPSHOT, status=Status[EIO<1014>: Fail to save snapshot.]]
        at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl.reportError(SnapshotExecutorImpl.java:691)
        at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl.onSnapshotSaveDone(SnapshotExecutorImpl.java:414)
        at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl$SaveSnapshotDone.continueRun(SnapshotExecutorImpl.java:145)
        at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl$SaveSnapshotDone.lambda$run$0(SnapshotExecutorImpl.java:141)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2022-05-31 12:12:14,899 JRaft-FSMCaller-Disruptor-0 WARN  [NodeImpl:2471] Node <G_snapshot_0530_P_1/192.168.109.52:13001> got error: {}.
Error [type=ERROR_TYPE_SNAPSHOT, status=Status[EIO<1014>: Fail to save snapshot.]]
        at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl.reportError(SnapshotExecutorImpl.java:691)
        at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl.onSnapshotSaveDone(SnapshotExecutorImpl.java:414)
        at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl$SaveSnapshotDone.continueRun(SnapshotExecutorImpl.java:145)
        at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl$SaveSnapshotDone.lambda$run$0(SnapshotExecutorImpl.java:141)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
What might be the possible reason of the error, can I have your support to have a look at it? Thanks.

**Comment by mareden** [comment]
@fengjiachun @killme2008 is there any further information for this question? If it's a bug, should I convert this question to an issue?

**Comment by killme2008** [comment]
@mareden  What's the jraft version are u using?

**Comment by mareden** [comment]
@killme2008 we're using jraft 1.3.10.bugfix_2.

**Comment by killme2008** [comment]
@mareden  Please provide more detail logs, it's not enough to dig up the problem.

**Comment by mareden** [comment]
@killme2008 I hope I can provide more detailed logs, but, unfortunately, all the log messages I've got have been pated in this comment: https://github.com/sofastack/sofa-jraft/issues/820#issuecomment-1144274865

**Comment by mareden** [comment]
@killme2008 in case the pasted messages are not enough, can you please provide a temporary release jar with new log entires in which you have interests, so that I can use it to capture enough log messages for your investigation purposes? Thanks.

**Comment by mareden** [comment]
A bug (https://github.com/sofastack/sofa-jraft/issues/857) has been reported for the issue discussed here, expecting that there could be more attention to this.

**Comment by mareden** [comment]
I'm closing this issue as it'll be tracked by bug #857
