### ISSUE TITLE
Follower节点Read-Index频繁超时，Leader节点正常

### ISSUE THREAD

**Issue by yufan022** [sofastack/sofa-jraft#859]
### Your question
当程序并发调用Leader/Follower全部节点线性一致性读查询接口时，发现Follower节点Read-Index读会频繁超时，而Leader节点不会出现该问题。

异常堆栈如下
```
2022-06-30 14:42:18 [read-index.timeout.scanner0] WARN...
 
        ...
        at com.alipay.sofa.jraft.closure.ReadIndexClosure$TimeoutTask.run(ReadIndexClosure.java:153) [xxx-SNAPSHOT.jar:?]
        at com.alipay.sofa.jraft.util.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:609) [xxx-SNAPSHOT.jar:?]
        at com.alipay.sofa.jraft.util.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:677) [xxx-SNAPSHOT.jar:?]
        at com.alipay.sofa.jraft.util.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:395) [xxx-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

状态机使用RocksDB实现，观察实际执行Get操作Latency不高，且同样的查询Leader不会报错，推测问题出现在JRaft层。

阅读代码发现Follower read-index行为和Leader不同，Read-Index时Follower需要从Leader Heartbeat获取index进度，会不会是这里heartbeat的间隔影响到了Follower的Read-Index吞吐和延迟？这里有哪些参数可以进行对应的优化缓解该问题呢？

目前来看TPS几千就会有很多超时，这样来看还不如直接将一致性查询走一遍状态机来实现性能好。

### Your scenes
调整electionTimeoutMs也无法缓解

### Environment

- SOFAJRaft version: 1.3.11
- JVM version (e.g. `java -version`): 11
- OS version (e.g. `uname -a`): linux
- Maven version:
- IDE version:

**Comment by killme2008** [comment]
Follower 并不只是靠心跳来推进 commitedIndex 进度的，包括每次 append entires 也会继续推进。主要问题在于 follower 做 read-index 需要多一跳到 leader 查询最新的 commitedIndex，并且还需要等待当前 state machine apply 也推进到 leader 返回的 commitedIndex， follower 本身 apply 会比 leader 有少许延迟，再加上 read-index 多这一跳，他的 readIndex 性能比 leader 差就不足为奇了。

因此 readindex 通常来说建议直接走 leader，如果 leader 是瓶颈，才去走 follower，如果走 follower，相应的 timeout 就需要设置的比 leader 更大。

另外，你可以观察下 leader 和 follower 的 apply index 推进进度上的差距。

**Comment by yufan022** [comment]
```
2022-07-01 00:53:33 [JRaft-RPC-Processor-1] WARN  xxx - safe get is not ok Status[EINTERNAL<1004>: RPC exception:Server thread pool busy when invoke with callback.The address is leaderhost:8080]
2022-07-01 00:53:33 [JRaft-RPC-Processor-1] INFO  xxx - error cost 4
2022-07-01 00:53:35 [read-index.timeout.scanner0] WARN  xxx - safe get is not ok Status[ETIMEDOUT<1010>: read-index request timeout]
2022-07-01 00:53:35 [read-index.timeout.scanner0] INFO  xxx - error cost 2002
```

Hi，经过进一步排查我发现Follower在高负载情况下，某些read-index请求出现了2次回调，第一次因为`Server thread pool busy when invoke with callback.`导致失败了没有处理，到了超时时间后 read-index.timeout.scanner会发起第二次超时`read-index request timeout`的回调。

我的场景Follower应该不是因为超时导致的timeout，应该是因为第一个thread busy的报错，导致的该任务不会继续处理了，所以最终会再次出现一个timeout的报错。

![image](https://user-images.githubusercontent.com/30121694/176809169-7dfd5445-5f7e-4b65-b958-37f517b110f7.png)

猜测这里是Follower处理read-index要请求Leader，对Leader的Raft线程池会造成压力，如果设置的不够大，就会引发`thread pool busy`报错。（线程池size=8，Follower的read-index TPS几千就会出现server thread pool busy）

这里处理方式是增大Leader的raft thread pool size么？另外这里也应该可以优化一下吧，尽量出现了`thread pool busy`报错后不要在`read-index.timeout.scanner`进行第二次超时的回调了。

**Comment by killme2008** [comment]
1. 不会重复，内部有做并发控制，你看到的应该是有部分请求确实超时
2. 调大 rpc 线程池 `NodeOptions#setRaftRpcThreadPoolSize`

**Comment by yufan022** [comment]
这里好像确实重复回调了

```
2022-07-01 00:53:33 [JRaft-RPC-Processor-1] WARN  xxx - safe get is not ok Status[EINTERNAL<1004>: RPC exception:Server thread pool busy when invoke with callback.The address is leaderhost:8080]
```
第一次报错
```
2022-07-01 00:53:35 [read-index.timeout.scanner0] WARN  xxx - safe get is not ok Status[ETIMEDOUT<1010>: read-index request timeout]
```
第二次报错

在第二次报错下边发现
```
java.lang.IllegalStateException: Stream is already completed, no further calls are allowed
```
此处回调使用GRPC响应，Stream在第一次报错正常返回后已经关闭了，而第二次重复回调了，导致报错。

这两次报错应该是同一个请求，据观察这种报错也是成对出现的，看现象是产生了2次回调，第一次`Server thread pool busy`正常响应了，第二次`read-index request timeout`响应失败了 因为GRCP Stream在第一次回调后已经关闭了。

**Comment by killme2008** [comment]
grpc 需要 @fengjiachun 看下。 bolt 应该没有这个问题。

**Comment by fengjiachun** [comment]
不会重复调用，跟用哪个 rpc 没有关系，并发控制逻辑见如下两行代码

https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/closure/ReadIndexClosure.java#L126

https://github.com/sofastack/sofa-jraft/blob/master/jraft-core/src/main/java/com/alipay/sofa/jraft/closure/ReadIndexClosure.java#L147

**Comment by yufan022** [comment]
jraft我用的bolt作为rpc通讯，上层read-index的rpc业务层我用的grpc

第一次`thread pool busy`报错是bolt的报错，这里发生第一次callback。理论上此时这次请求应该就终止了，不应该再出现第二次的`read-index request timeout`的callback了吧？而且观察日志，两个报错却是成对出现，每次都是先`thread pool busy` 然后超过超时时间在出现`request timeout`。

因为我的read-index查询接口在第一次回调grpc就已经返回了，所以第二次回调时会出现`Stream is already completed`，晚点我debug想办法复现一下，看下为什么这里会出现2次回调。

**Comment by fengjiachun** [comment]
先关闭了，有新的发现可以再打开
