### ISSUE TITLE
"LocalRaftMetaStorage not initialized" error

### ISSUE THREAD

**Issue by alexei-osipov** [sofastack/sofa-jraft#866]
I've got this error message:
```
java.lang.IllegalStateException: LocalRaftMetaStorage not initialized
	at com.alipay.sofa.jraft.storage.impl.LocalRaftMetaStorage.checkState(LocalRaftMetaStorage.java:153)
	at com.alipay.sofa.jraft.storage.impl.LocalRaftMetaStorage.setVotedFor(LocalRaftMetaStorage.java:172)
	at com.alipay.sofa.jraft.core.NodeImpl.handleRequestVoteRequest(NodeImpl.java:1801)
	at com.alipay.sofa.jraft.rpc.impl.core.RequestVoteRequestProcessor.processRequest0(RequestVoteRequestProcessor.java:56)
	at com.alipay.sofa.jraft.rpc.impl.core.RequestVoteRequestProcessor.processRequest0(RequestVoteRequestProcessor.java:34)
	at com.alipay.sofa.jraft.rpc.impl.core.NodeRequestProcessor.processRequest(NodeRequestProcessor.java:60)
	at com.alipay.sofa.jraft.rpc.RpcRequestProcessor.handleRequest(RpcRequestProcessor.java:53)
	at com.alipay.sofa.jraft.rpc.RpcRequestProcessor.handleRequest(RpcRequestProcessor.java:35)
	at com.alipay.sofa.jraft.rpc.impl.BoltRpcServer$2.handleRequest(BoltRpcServer.java:124)
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.dispatchToUserProcessor(RpcRequestProcessor.java:235)
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.doProcess(RpcRequestProcessor.java:146)
	at com.alipay.remoting.rpc.protocol.RpcRequestProcessor$ProcessTask.run(RpcRequestProcessor.java:393)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
```

Does that error means that I'm doing something wrong with `sofa-jraft`?
So far this specific error was observed only once. So I can't provide steps for problem reproduction.

### Environment

- SOFAJRaft version: 1.3.11
- JVM version (e.g. `java -version`): 11.0.15
- OS version (e.g. `uname -a`): Windows 10

**Comment by killme2008** [comment]
It may happen when node is starting up, but it's fine here, the prevVote request will be sent and processed again after node starts up.
