### ISSUE TITLE
jraft-rheakv 无法直接使用grpc进行通信

### ISSUE THREAD

**Issue by lfygh** [sofastack/sofa-jraft#885]
Exception in thread "main" java.lang.NullPointerException: null default instance: com.alipay.sofa.jraft.rhea.cmd.store.GetRequest
	at com.alipay.sofa.jraft.util.Requires.requireNonNull(Requires.java:55)
	at com.alipay.sofa.jraft.rpc.impl.GrpcServer.registerProcessor(GrpcServer.java:133)
	at com.alipay.sofa.jraft.rhea.StoreEngineHelper.addKvStoreRequestProcessor(StoreEngineHelper.java:94)

应该是没有自动注册rhea cmd相关的序列化和反序列化，即没有调用rpcFactory.registerProtobufSerializer()

**Comment by fengjiachun** [comment]
你好，rheakv 没有支持 grpc，主要是序列化部分不支持，有兴趣可以考虑贡献一个 PR
